#server:
#  port: 8301
# 启动多个实例 配置中修改端口
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.191.101:3306/clouddemo
    username: root
    password: 123456
  application:
    name: userservice
eureka:
  client:
    service-url:
#      defaultZone:  http://127.0.0.1:8888/eureka
      # 注册到两个eurekaserver中
      defaultZone:  http://eureka1:8801/eureka,  http://eureka2:8802/eureka