server:
  port: 8303

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.191.101:3306/clouddemo
    username: root
    password: 123456
  application:
    name: borrowservice

eureka:
  client:
    service-url:
#      defaultZone:  http://127.0.0.1:8888/eureka
      # 注册到两个eurekaserver中
      defaultZone:  http://eureka1:8801/eureka,  http://eureka2:8802/eureka
feign:
  circuitbreaker:
    enabled: true #支持熔断
#actuator 暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'